services:
  account_manager:
    build:
      context: ./account_manager
      dockerfile: Dockerfile
    image: account_manager
    container_name: account_manager
    ports:
      - "8000:8000"
    volumes:
      - ./account_manager:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
